/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthTest: typeof import('./src/components/AuthTest.vue')['default']
    BlogPage: typeof import('./src/components/BlogPage.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    ContactPage: typeof import('./src/components/ContactPage.vue')['default']
    Cropper2: typeof import('./src/components/Cropper2.vue')['default']
    CropperPage: typeof import('./src/components/CropperPage.vue')['default']
    EmpView: typeof import('./src/components/EmpView.vue')['default']
    GalleryPage: typeof import('./src/components/GalleryPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupPage: typeof import('./src/components/SignupPage.vue')['default']
    UserView: typeof import('./src/components/UserView.vue')['default']
  }
}
